// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB8SpaMiBzGqVgR5gQapP7exRu7mqRTGA',
    appId: '1:281399238332:web:edc2372148fa142231bab9',
    messagingSenderId: '281399238332',
    projectId: 'messagingapp-88c03',
    authDomain: 'messagingapp-88c03.firebaseapp.com',
    storageBucket: 'messagingapp-88c03.appspot.com',
    measurementId: 'G-MFR3S5EP9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBhbUf7cAJlgM42OtRHeUh9xMZrRDZ2Ck',
    appId: '1:281399238332:android:b641d3c91396d40b31bab9',
    messagingSenderId: '281399238332',
    projectId: 'messagingapp-88c03',
    storageBucket: 'messagingapp-88c03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL4ZWWFsm3Me49BUE80FQFfNtaIfeYVyA',
    appId: '1:281399238332:ios:677d0f6ec23feb2a31bab9',
    messagingSenderId: '281399238332',
    projectId: 'messagingapp-88c03',
    storageBucket: 'messagingapp-88c03.appspot.com',
    iosBundleId: 'com.example.messagingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL4ZWWFsm3Me49BUE80FQFfNtaIfeYVyA',
    appId: '1:281399238332:ios:d6040cc9084e797c31bab9',
    messagingSenderId: '281399238332',
    projectId: 'messagingapp-88c03',
    storageBucket: 'messagingapp-88c03.appspot.com',
    iosBundleId: 'com.example.messagingapp.RunnerTests',
  );
}
